[project]
name = 'bitcoin-credit-protocol'
description = 'Bitcoin-Native Uncollateralized Credit Protocol on Stacks'
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[contracts.mock-usdcx]
path = 'contracts/mock-usdcx.clar'
clarity_version = 4
epoch = '3.3'

[contracts.credit-identity]
path = 'contracts/credit-identity.clar'
clarity_version = 4
epoch = '3.3'

[contracts.credit-oracle]
path = 'contracts/credit-oracle.clar'
clarity_version = 4
epoch = '3.3'

[contracts.loan-vault]
path = 'contracts/loan-vault.clar'
clarity_version = 4
epoch = '3.3'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
